del /s *.~*
del /s *.dcu
del /s *.txt
del /s *.ppu
del /s *.dsk
del /s *.bak
del /s *.identcache
del /s *.otares
del /s *.local
del /s *.cfg
del /s *.ddp
del /s *.a
del /S *.*proj.local
del /S *.tvsconfig
